### ISSUE TITLE
Add function to select collection to work with

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-colab#12]
The latest version of the data feedback template includes [code to help an analyst find the correct collection to work with](https://colab.research.google.com/drive/1Q1L4uZYYGFyj_pGkot5LipxMrgzeJvuy#scrollTo=wePWY1jj88m_) (broadly, select a source_id and return a list of collections for that source, with a count of releases, records and compiled_releases for each collection).

This is applicable to any use of a notebook to connect to kingfisher, so would be a good candidate for inclusion in kingfisher-colab

**Comment by duncandewhurst** [comment]
There have been some changes since this issue was originally opened: the functions in the feedback notebook have been refined, the release, records and compiled release counts have been incorporated into the collections table and a new function has been added to select the views schema to work with.

These are still common tasks for anyone working with kingfisher in a notebook, so would be good to incorporate into the library.

**Comment by jpmckinney** [comment]
So perhaps:

* `list_sources(pattern)` returns a list of matching source IDs
* `list_collections(source_id)` returns a list of collections of that source

Is that it?

**Comment by jpmckinney** [comment]
Done in 0.2.0.
