### ISSUE TITLE
Setup Repository

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-colab#15]
James,

Can you enable https://travis-ci.org/open-contracting/kingfisher-colab and also set up https://readthedocs.org/projects/kingfisher-colab/ with an incoming webhook?

Thanks,
James

**Comment by jpmckinney** [comment]
Done! https://travis-ci.org/open-contracting/kingfisher-colab

I added the webhook as well via ReadTheDocs admin.
