### ISSUE TITLE
FYI we're using this code in 360Giving data services

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher-colab#17]
Hi team! 

Just an FYI to say that we're using this code in some work we're doing on 360Giving Colab notebooks. We're using specific commits so no need to adapt practice or anything - just to let you know, say thanks, and ping us if you'd like to see what we're using and talk about contributions!

**Comment by jpmckinney** [comment]
Thanks for the note! Please let me know if that work leads to any desired changes to this repo and/or any copying or extraction of code from this repo.

Like with bods-babel and bodskit, whose behaviors were retroactively integrated into ocds-babel and ocdskit, I think we can design for shared code, as long as we talk about it early on :)

**Comment by jpmckinney** [comment]
@robredpath FYI, this package is now versioned, so 360Giving should be able to use specific versions rather than specific commits. The docs include a changelog. https://kingfisher-colab.readthedocs.io/en/latest/changelog.html

cc @drkane @morchickit
