### ISSUE TITLE
Can download_package_from_ocid have an ORDER clause?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-colab#19]
Sorting by date ASC might make sense?

**Comment by pindec** [comment]
Yeah, having an order by clause would be helpful for OCIDs with many releases. 

Order by date as default seems sensible - although I probably use date DESC more often. 

We could also make both options (what field, DESC or ASC) overridable with parameters, but given there's no order by at present that might be overkill :).

**Comment by jpmckinney** [comment]
So something like `ORDER BY data ->> 'date' DESC`?
