### ISSUE TITLE
Need to fix version of openpyxl in kingfisher-colab

### ISSUE THREAD

**Issue by pindec** [open-contracting/kingfisher-colab#20]
Looks like an openpyxl upgrade means that flattening OCDS via kingfisher colab currently fails with the following error:

"got invalid input value of type <class 'xml.etree.ElementTree.Element'>, expected string or Element".

[Example OCDS JSON that fails is here](https://gist.github.com/pindec/5b42f0e3c3c41a69805c3f0037322e00)

As a workaround for now, add
`!pip install -U openpyxl==2.5.9`
below the `!pip install -U git+https://github.com/open-contracting/kingfisher-colab` line.

**Comment by pindec** [comment]
[Related issue on flatten-tool](https://github.com/OpenDataServices/flatten-tool/issues/328)

**Comment by jpmckinney** [comment]
This seems to have been fixed upstream.
