### ISSUE TITLE
List of regularly used notebooks

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-colab#25]
@yolile @romifz @aguilerapy @duncandewhurst @pindec @mrshll1001 Please share links to notebooks / folders of notebooks that are regularly used, so that development on this library can keep that in mind.

**Comment by mrshll1001** [comment]
[This is the latest Data Feedback notebook](https://colab.research.google.com/drive/1lpWoGnOb6KcjHDEhSBjWZgA8aBLCfDp0) which is the one I'd always want kept in mind as we derive our data feedback colabs from it.

**Comment by jpmckinney** [comment]
Thanks, @mrshll1001. I fixed the install line. Can you let me know if it works? I did "Run all" and did a very quick read. There should just be deprecation warnings now.

**Comment by jpmckinney** [comment]
I fixed one issue in 0.1.1 (`output_notebook` and `getResults` had stopped returning data). I've added a link to the notebook in the tests, as a reminder to test manually.
