### ISSUE TITLE
Please add jpmckinney to kingfisher-colab PyPi project

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-colab#26]
https://pypi.org/project/kingfisher-colab/

Since I wasn't added when it was originally created, and since it was never communicated that this package was created (the release process used didn't add tags on GitHub, which would have at least been a hint, and the released package isn't used in any notebook I've seen), I ended up creating another project: https://pypi.org/project/ocdskingfishercolab/

Please either delete the project from PyPi to avoid confusion, and/or add me as an admin.

**Comment by robredpath** [comment]
This is now done. @jpmckinney has been added to https://pypi.org/project/kingfisher-colab/ and has now deleted it.

**Comment by jpmckinney** [comment]
Deleted on PyPi. ocdskingfishercolab==0.0.1 can be used as drop-in replacement as it is the same code.
