### ISSUE TITLE
SQL syntax highlighting

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-colab#30]
I've been trying to get SQL syntax highlighting working in Google Colab with no luck.

If we start using ipython-sql (#29) then it would be helpful to also have syntax highlighting cells which use the %%sql cell magic.

Stackoverflow suggests this is possible with a normal Jupyter notebook: https://stackoverflow.com/questions/57966403/how-to-add-syntax-highlight-to-sql-line-magic-cell-magic-and-custom-command-in

This might not fit exactly kingfisher-colab, as I expect the solution will be something of a hack involving custom Javascript, but it seems like the closest place to log it.

**Comment by jpmckinney** [comment]
Did the solution from StackOverflow work? It looks like it involves a JavaScript cell. I figure we can document this solution in Kingfisher Colab, but I think it's too much to call into JavaScript from Python.

**Comment by duncandewhurst** [comment]
It involves putting the Javascript in `~/.jupyter/custom/custom.js` (as described in the [linked answer](https://stackoverflow.com/questions/43641362/adding-syntax-highlighting-to-jupyter-notebook-cell-magic/43686552)) but I fell down on how to do that in Colaboratory.

**Comment by jpmckinney** [comment]
Hmm, I don't think it's possible to configure that in Colaboratory.

**Comment by jpmckinney** [comment]
It seems to highlight Markdown code blocks of SQL inside Python, but I guess it doesn't yet highlight actual code blocks? https://colab.research.google.com/notebooks/editor_details.ipynb#scrollTo=bEXkvERUtU5O

**Comment by duncandewhurst** [comment]
Ah interesting, I don't get any highlighting in code blocks.

> Hmm, I don't think it's possible to configure that in Colaboratory.

I wondered if there was some way to 'inject' that Javascript another way, e.g. https://github.com/Lor-Saba/Code-Injector

**Comment by jpmckinney** [comment]
Can you try this? https://github.com/catherinedevlin/ipython-sql/issues/41#issuecomment-354679781

You can change the code to work with both `%sql` and `%%sql`: https://github.com/catherinedevlin/ipython-sql/pull/75#issuecomment-354680166

Note that it might fail on Chrome and Firefox... https://github.com/catherinedevlin/ipython-sql/pull/93

**Comment by duncandewhurst** [comment]
Hmm, I don't get an error in Colaboratory when I execute the code from https://github.com/catherinedevlin/ipython-sql/issues/41#issuecomment-354679781 in a cell, but I also don't get any syntax highlighting.

Looking in the Web Console I can see the following error:

```
Error evaluating Javascript output:  ReferenceError: IPython is not defined
```

**Comment by jpmckinney** [comment]
I can't find any highlighting code in https://github.com/googlecolab/colabtools or https://github.com/googleapis/python-bigquery so not sure where Colaboratory is doing its highlighting of BigQuery SQL.

(Regarding the highlighting mentioned in https://cloud.google.com/blog/products/data-analytics/whats-the-weather-like-using-colab-to-get-more-out-of-bigquery)

**Comment by jpmckinney** [comment]
Found it. https://github.com/googlecolab/colabtools/issues/216 refers to https://colab.research.google.com/v2/external/external_polymer_binary.js, where I see code like: `multilineFunctions:[ ... {name:"read_gbq",language:"googlesql"}]` and `a.cellMagics.push({name:"bigquery",language:"googlesql"}`. So, that explains why code is highlighted in `read_gbq` and in `%%bigquery` magic cells. However, that file's behavior can't be changed except by Google.

**Comment by jpmckinney** [comment]
Based on last comment, this isn't possible without a change by Google.

It also doesn't look like anyone has authored a relevant browser extension for Colaboratory:

https://chrome.google.com/webstore/search/syntax%20highlighting?hl=en
https://chrome.google.com/webstore/search/colaboratory?hl=en

**Comment by kindly** [comment]
Just thought I would ask!!!
https://github.com/googlecolab/colabtools/issues/2039
