### ISSUE TITLE
SQL style guide and linter

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-colab#31]
We write a lot of SQL code in notebooks. To make it easier to maintain and collaborate on that code it would be good to agree on a style guide to follow and to use a linter to enforce that style guide.

[pycodestyle_magic](https://github.com/mattijn/pycodestyle_magic) provides a nice integration of flake-8 and the notebook interface and [https://github.com/pgjones/flake8-sql](https://github.com/pgjones/flake8-sql) is a flake-8 plugin that looks for SQL queries in Python code and checks them against an opinionated style, based on the [SQL Style Guide](http://www.sqlstyle.guide/).

It looks like we could use those to lint our existing approach of passing SQL queries as strings, although I haven't actually tried it.

[SQLFluff](https://docs.sqlfluff.com/en/latest/index.html) is more configurable and has a default style which is closer to our existing style, but seems to only be available as a command-line tool.

If we choose to adopt ipython-sql (#29) then some further work would be required to get linting working for cells which use the `%%sql` magic.

@pindec @mrshll1001 @odscrachel @yolile @romifz - does this sound like a good idea? Do you have a preferred style guide we should follow?

**Comment by jpmckinney** [comment]
For Kingfisher Views I use pgformatter (command-line only, but more popular than sqlfluff and others): https://kingfisher-views.readthedocs.io/en/latest/develop/sql.html#format-sql

Looks like pycodestyle_magic can configure the entire notebook: https://github.com/mattijn/pycodestyle_magic#to-auto-check-each-cell-version--03 Would need to test if flake8-sql integrates properly.

We can also consider storing our common notebooks in a (private) GitHub repository. See Google Colab integration here: https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb

If the notebooks are in a GitHub repo, we can use command-line tools like https://pypi.org/project/flake8-nb/

**Comment by duncandewhurst** [comment]
Storing the template notebooks in Github could be useful, but rather than using a command-line tool for linting I'd prefer to have:

* Feedback within the notebooks (as in pycodestyle_magic), so it that we can correct and tidy code as we go, rather than only when saving to a repo
* Linting available in all notebooks, not just those we save to Github, as we often collaborate on additional code in our own copies of the templates when investigating issues with publisher data

Ideally, we'd also be able to use pycodestyle_magic's Python linting, so that by default cells are linted as Python, unless they use the `%%sql` magic, in which case they'd be linted as SQL.

**Comment by duncandewhurst** [comment]
@pindec @mrshll1001 @odscrachel @yolile @aguilerapy - what are your thoughts? Should we prioritise this for the upcoming sprint?

**Comment by pindec** [comment]
Yes, notebook-level lint-ing regardless of sharing would be helpful.

**Comment by duncandewhurst** [comment]
In lieu of in-notebook linting, I've added an action to the notebooks-ocds repo to lint SQL cells for the notebooks in the repo: https://github.com/open-contracting/notebooks-ocds/pull/15

**Comment by jpmckinney** [comment]
Once that PR is merged, is this issue closed? If not, what remains?

**Comment by duncandewhurst** [comment]
Well, the ideal would be in-notebook linting, but @kindly looked into it and it isn't possible in Colab with ipython-sql. However, David has looked into a partial solution as part of his work on https://github.com/OpenDataServices/noteql, which we might want to adopt in the future.

**Comment by jpmckinney** [comment]
Ok, closing as the only available full and implementable solutions have been implemented.
