### ISSUE TITLE
Dependencies of google-colab 1.0.0 are now different on Google Colab compared to PyPI

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/kingfisher-colab#38]
Since we've pinned based on what's in PyPI (and presumably used to be on Colab), we now get these errors on Colab:

```
ERROR: google-colab 1.0.0 has requirement notebook~=5.3.0; python_version >= "3.0", but you'll have notebook 5.2.2 which is incompatible.
ERROR: google-colab 1.0.0 has requirement requests~=2.23.0, but you'll have requests 2.21.0 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
```

This doesn't seem to break the notebook, as we just get one alternative of the incompatible requirements installed. I think this may change (to hard fail) in future pip versions.

![Screenshot from 2020-12-15 11-57-06](https://user-images.githubusercontent.com/634/102212432-21219980-3ecd-11eb-8f20-d30046ec70c8.png)

**Comment by jpmckinney** [comment]
We should use whatever works on Colab.

Annoying that Google doesn’t update PyPi.

**Comment by Bjwebb** [comment]
> Annoying that Google doesn’t update PyPi.

Yeah, the worst bit is on colab they've changed the dependencies, but kept the version number of google-colab the same.

**Comment by jpmckinney** [comment]
I made the changes for `notebook` and `requests` (which seemed to get rid of the folium warning). I'm not sure what requires folium. Of course, we'll then get similar warnings in local notebooks (and in CI), but I think these are much less frequent.

**Comment by duncandewhurst** [comment]
I'm still seeing these errors in Colab, does a new version need to be released on PyPi?

**Comment by jpmckinney** [comment]
First, can you test if installing from GitHub produces errors?

`pip install -e git+https://github.com/open-contracting/kingfisher-colab.git#egg=ocdskingfishercolab`

**Comment by duncandewhurst** [comment]
Sorry for the delay in getting back to this.

Installing from Github produces no errors.

**Comment by jpmckinney** [comment]
Thanks. Having confirmed the new code works, I've released 0.3.1.

**Comment by duncandewhurst** [comment]
Hmmm, looks like the new version now installs an older version of ipython-sql (0.3.9) which causes some other errors when setting configuration variables and connecting to a database.

Does this line need reinstating? https://github.com/open-contracting/kingfisher-colab/commit/670240691f69d3426d107dce82b1f0c4862b0ce4#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L26

**Comment by jpmckinney** [comment]
The google-colab package is overly specific with its version numbers, causing [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell).

As a result, the new version of Kingfisher Colab doesn't specify any versions, and instead lets pip reconcile versions that are compatible.

Try installing in a fresh notebook with `pip install kingfisher-colab ipython-sql~=0.4.0`. If it succeeds, we can update this package.

Otherwise, the only way to resolve dependency hell is for the user to manually install the versions they want as a separate step.

**Comment by duncandewhurst** [comment]
Assuming you meant `pip install ocdskingfishercolab ipython-sql~=0.4.0` that does indeed succeed.

**Comment by jpmckinney** [comment]
Ok, should work with 0.3.2 now.

**Comment by duncandewhurst** [comment]
Confirmed working on 0.3.2 - thanks!
