### ISSUE TITLE
set_search_path: ResourceClosedError

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-colab#39]
`set_search_path` works but returns a `ResourceClosedError`, e.g.

```
schema_name = 'view_data_collection_2052_2053'

set_search_path(schema_name)

---------------------------------------------------------------------------

ResourceClosedError                       Traceback (most recent call last)

<ipython-input-12-1fd85f0312b5> in <module>()
      1 schema_name = 'view_data_collection_2052_2053'
      2 
----> 3 set_search_path(schema_name)

12 frames

<decorator-gen-116> in execute(self, line, cell, local_ns)

<decorator-gen-115> in execute(self, line, cell, local_ns)

/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py in raise_(***failed resolving arguments***)
    209 
    210         try:
--> 211             raise exception
    212         finally:
    213             # credit to

ResourceClosedError: This result object does not return rows. It has been closed automatically.

```

**Comment by jpmckinney** [comment]
Link to notebook? This command is doing nothing more than:

```
%sql SET search_path = {schema_name}, public
```

**Comment by jpmckinney** [comment]
Try the above. If the error occurs in both cases, then it can't be fixed in Colab.

**Comment by yolile** [comment]
> Try the above. If the error occurs in both cases, then it can't be fixed in Colab.

Same error. The search path is set, though, so maybe we can add a try-catch to the method and ignore the error?

**Comment by jpmckinney** [comment]
That might hide an actual error, though. Does it occur across all notebooks? Try in a fresh notebook?

**Comment by yolile** [comment]
[Here](https://colab.research.google.com/drive/1sS7-MW0u-rZ428C8ea6WeOCEJtT5lZTL?authuser=1#scrollTo=GHRE428DLQmd) you can find the colab I'm using.  I think that the problem is that probably the SQL magic function is meant to be used for SELECT queries and not for non-returning queries as set search path, updates, inserts, etc

**Comment by jpmckinney** [comment]
What if you use `%%sql` ?

**Comment by yolile** [comment]
![image](https://user-images.githubusercontent.com/6834122/115067659-3b8d7300-9ebf-11eb-842e-9513f1e4cebb.png)
same

**Comment by jpmckinney** [comment]
Can you report an issue to https://github.com/catherinedevlin/ipython-sql ? 

The problem is `resultset = ResultSet(result, statement, config)` in `sql/run.py`. It should handle statements without rows returned.

In the meantime, we can add a try/except here.

**Comment by jpmckinney** [comment]
New release available: https://pypi.org/project/ocdskingfishercolab/0.3.4/
