### ISSUE TITLE
Consider using noteql instead of ipython-sql

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-colab#50]
@kindly has been working on [noteql](https://github.com/OpenDataServices/noteql) as an alternative to ipython-sql. The new library fixes some of the issues we have with ipython-sql (e.g. https://github.com/catherinedevlin/ipython-sql/issues/177, https://github.com/catherinedevlin/ipython-sql/issues/190, https://github.com/catherinedevlin/ipython-sql/issues/191) and introduces some new features, including support for multiple SQL statements in one cell and support for templating using [jinjasql](https://github.com/sripathikrishnan/jinjasql).

noteql is still a work-in-progress but could be worth using in the future, especially as we'll be more readily able to make changes or add features.

@kindly are there any other improvements, either from an analyst perspective, or from a development/maintenance perspective, that we should take into account?

**Comment by jpmckinney** [comment]
Happy to consider once there is an update on noteql's progress and an assessment against the linked criteria.

**Comment by jpmckinney** [comment]
See #68
