### ISSUE TITLE
PyDrive is deprecated and unmaintained

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-colab#52]
https://github.com/googlearchive/PyDrive

https://github.com/iterative/PyDrive2 is recommended instead.

**Comment by duncandewhurst** [comment]
This change breaks the `save_dataframe_to_spreadsheet` function. Minimal notebook to reproduce the issue: [notebook](https://colab.research.google.com/drive/1MWGBcoeuMrcatSaelORgWMH5OMhxOlX4). I also tested the relevant authenticate code for both PyDrive and PyDrive2 in a [notebook](https://colab.research.google.com/drive/1g_5m23M573L8cDclrrowOalHND3o-KNC?usp=sharing).

**Comment by jpmckinney** [comment]
Did you modify the second notebook after running it? The first code snippet uses pydrive2 and fails as it's not installed.

**Comment by duncandewhurst** [comment]
Whoops, copy-paste error. Now fixed!

**Comment by jpmckinney** [comment]
Looking into it. PyDrive2 was forked from this point: https://github.com/iterative/PyDrive2/compare/cf58f81efa67cb30f7c9b3da7d304f214a9b6d3b..HEAD

**Comment by jpmckinney** [comment]
I'm not seeing any relevant differences in PyDrive's auth.py. My guess at this point is that Google Colab monkey-patches their own library to behave differently in the Colab environment.

**Comment by jpmckinney** [comment]
Yup, that’s what they do: https://github.com/googlecolab/colabtools/blob/7c5503e6cdaa23971c08b5a3f5a6d23667a753cb/google/colab/_import_hooks/_pydrive.py

**Comment by jpmckinney** [comment]
@duncandewhurst Can you test kingfisher-colab using the new commit? I edited your second notebook (it wouldn't save though), and the approach worked there.

**Comment by duncandewhurst** [comment]
The new commit fixes the issue. Good sleuthing!

**Comment by jpmckinney** [comment]
0.3.9 is released: https://pypi.org/project/ocdskingfishercolab/
