### ISSUE TITLE
Document each function in kingfisher-colab

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-colab#6]
At the moment I have to look at the code in __init__.py to work out how to use the functions.

Some documentation, perhaps in the style of the [ocdskit documentation](https://github.com/open-contracting/ocdskit) would be really helpful.

- [ ] create_connection
- [ ] authenticate_gspread
- [ ] authenticate_pydrive
- [ ] getResults
- [ ] saveToCSV
- [ ] set_spreadsheet_name
- [ ] saveToSheets
- [ ] downloadReleases
- [ ] output_ghseet
- [ ] output_flattened_gsheet
- [ ] output_notebook
- [ ] download_json

**Comment by jpmckinney** [comment]
I think the Extension Registry Python Package is a better example to follow. There's a 'cover page' about [programmatic access](https://ocdsextensionregistry.readthedocs.io/en/latest/library.html) with examples, written as a separate RST file. There is then [reference documentation](https://ocdsextensionregistry.readthedocs.io/en/latest/library.html#api-documentation), automatically extracted from the `.py` files. Having that lower-level documentation co-located with the code means that it's more likely to be kept up-to-date.

**Comment by jpmckinney** [comment]
This was started in 7338ab6f1494d7c8ee825e159cfa1b898b438ccd.
