### ISSUE TITLE
calculate_coverage: Potential error in default scope

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-colab#61]
If a field is `contracts/implementation/documents/format`, then `contracts_summary` is used as the scope, instead of `contract_implementation_documents_summary`, because `contract` != `contracts`.

If that's the intended behavior, the documentation can be updated. If not, the error can be fixed.

**Comment by jpmckinney** [comment]
I refactored `calculate_coverage`. Just noting that for this and the other issues I opened, you can checkout 7da376e849823c326ce96d9f38142a6b334206c9 to see that the behavior was the same before the refactor.

**Comment by jpmckinney** [comment]
@yolile @camilamila Tagging you as well, since you might be using this function.

**Comment by duncandewhurst** [comment]
That looks like an error to me, I would expect `contract_implementation_documents_summary` to be the default scope.

**Comment by duncandewhurst** [comment]
> I refactored calculate_coverage. Just noting that for this and the other issues I opened, you can checkout https://github.com/open-contracting/kingfisher-colab/commit/7da376e849823c326ce96d9f38142a6b334206c9 to see that the behavior was the same before the refactor.

I reviewed the other issues and the changes look good. I ran the queries in the [demo notebook](https://colab.research.google.com/drive/1-B2Wqd-uebpNv8bImEzk1lGSiJIxDqDX) using the latest version of kingfisher colab in this repo and there were no changes to the output compared to when it was originally run.

**Comment by jpmckinney** [comment]
FYI, this would also change:

* award_suppliers
* award_items
* award_documents
* contract_items
* contract_documents
* contract_milestones
* contract_implementation_transactions
* contract_implementation_milestones

**Comment by jpmckinney** [comment]
I've pushed the fix. I can make a release anytime, but wanted to give some time to test.
