### ISSUE TITLE
Add download_json function

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-colab#9]

**Comment by jpmckinney** [comment]
What is this method intended to do?

**Comment by jpmckinney** [comment]
Copying code here, as it's unusual to have an unimplemented function in a library.

```python
def download_json(root_list_path, sql, params=None):
    # data column needs to be in results
    raise NotImplementedError
```

**Comment by duncandewhurst** [comment]
> What is this method intended to do?

Accept a sql query which returns a `data` column containing either OCDS releases or records and save a JSON package of those releases or records to the user's local machine (see [`files.download`](https://github.com/googlecolab/colabtools/blob/master/google/colab/files.py#L129))

**Comment by jpmckinney** [comment]
Added `download_package_from_query` in 0.1.0.
